### ISSUE TITLE
the segmentation speed is too slow on Android

### ISSUE THREAD

**Issue by lawo123** [sacmehta/EdgeNets#28] opened 2020-03-07 07:39 UTC
I deployed the segmentation model to android by ncnn,the inference cost 400ms,image_size=512*512.How to increase speed？

**Comment by sacmehta** [comment] 2020-03-10 04:39
Are you running on CPU? Which task are you running? If its a detection task, you might want to use 300x300 resolution?

**Comment by lawo123** [comment] 2020-03-10 06:06
I run segmentation task on Android gpu,scales = 2.My picture is 1024 ×720,so i pretrained model to 512*512 resolution.

**Comment by sacmehta** [comment] 2020-03-10 17:46
Could you benchmark different stages (frame reading/processing, model execution, overlay etc.) to understand the bottleneck?

**Comment by sacmehta** [comment] 2020-05-05 17:20
I think the issue is solved, so closing now

**Closed by sacmehta** 2020-05-05 17:20 UTC
